import Link from "next/link";
import Navbar from "@/sections/Navbar";
import Footer from "@/sections/Footer";
import { rteConfig, rteDocuments } from "@/app/data/rte";

const statusLabels = { available: "Documento disponible", pending: "Pendiente de publicación", "not-applicable": "No aplica a este proceso" };
const statusStyles = { available: "bg-green-100 text-green-800", pending: "bg-amber-100 text-amber-800", "not-applicable": "bg-gray-200 text-gray-600" };

export default function Rte2026Page() {
  return <main className="bg-black text-white min-h-screen"><Navbar />
    <section className="pt-40 md:pt-48 pb-24 px-6"><div className="max-w-7xl mx-auto"><p className="text-xs text-gray-500 mb-16"><Link href="/transparencia" className="hover:text-white">Transparencia</Link> / <Link href="/transparencia/rte" className="hover:text-white">RTE</Link> / 2026</p><div className="grid md:grid-cols-[1fr_350px] gap-16 items-end"><div><p className="uppercase tracking-[0.4em] text-red-500 text-sm mb-6">Régimen Tributario Especial — RTE</p><h1 className="text-6xl md:text-8xl font-black tracking-[-0.06em] leading-[0.88]">Solicitud de<br />Calificación 2026</h1></div><aside className="border border-white/15 p-7"><p className="uppercase tracking-[0.22em] text-[10px] text-gray-500">Estado del proceso</p><strong className="text-2xl flex items-center gap-3 mt-5"><span className="w-2 h-2 rounded-full bg-amber-400" />En preparación</strong><p className="text-gray-500 text-sm mt-4">El estado se actualiza únicamente con soporte documental.</p></aside></div></div></section>
    <section className="bg-[#dedbd4] text-black px-6 py-24"><div className="max-w-7xl mx-auto"><h2 className="text-4xl md:text-5xl font-black mb-12">Ficha institucional</h2><div className="grid md:grid-cols-2 gap-px bg-black/15">{[
      ["Razón social", rteConfig.legalName], ["NIT", rteConfig.nit], ["Tipo de entidad", "Corporación / Entidad sin ánimo de lucro"], ["Proceso RTE", "Calificación"], ["Año", "2026"], ["Actividad meritoria", "Pendiente de validación con el Formulario 5245"], ["Domicilio", "Pendiente de validación documental"], ["Representante legal", "Pendiente de validación documental"], ["Entidad de inspección, vigilancia o control", "Pendiente de validación documental"]
    ].map(([label,value]) => <div key={label} className="bg-[#f3f1ec] p-7 min-h-28"><span className="uppercase tracking-[0.2em] text-[10px] text-gray-500 block mb-3">{label}</span><strong className={value.startsWith("Pendiente") ? "text-amber-800 font-medium" : "font-bold"}>{value}</strong></div>)}</div></div></section>
    <section className="bg-[#f7f5f0] text-black px-6 py-24"><div className="max-w-7xl mx-auto"><div className="grid md:grid-cols-2 gap-12 mb-16"><div><p className="uppercase tracking-[0.4em] text-red-600 text-xs mb-5">Repositorio documental</p><h2 className="text-5xl md:text-7xl font-black tracking-[-0.05em]">Documentación<br />RTE 2026</h2></div><p className="text-gray-600 leading-relaxed self-end max-w-xl">Los estados diferencian información disponible, pendiente y no aplicable. No se publican archivos provisionales, enlaces vacíos ni datos sin validar.</p></div><div className="border-t border-black/20">{rteDocuments.map(doc => <article key={doc.id} className="grid md:grid-cols-[70px_1fr_220px] gap-6 py-8 border-b border-black/15 items-center"><span className="text-xs text-gray-400">{doc.id}</span><div><p className="uppercase tracking-[0.2em] text-[10px] text-gray-500 mb-2">{doc.category} · {doc.year}</p><h3 className="text-xl md:text-2xl font-black mb-2">{doc.title}</h3><p className="text-gray-600 leading-relaxed max-w-3xl">{doc.description}</p>{doc.status === "available" && doc.fileUrl && <div className="flex gap-4 mt-5"><a href={doc.fileUrl} target="_blank" rel="noreferrer" className="text-xs font-bold text-red-600">Ver documento</a><a href={doc.fileUrl} download className="text-xs font-bold">Descargar PDF</a></div>}</div><span className={`rounded-full px-5 py-3 text-[10px] uppercase tracking-[0.12em] font-bold text-center ${statusStyles[doc.status]}`}>{statusLabels[doc.status]}</span></article>)}</div></div></section>
    <section className="px-6 py-24 bg-[#151516]"><div className="max-w-7xl mx-auto"><p className="uppercase tracking-[0.4em] text-red-500 text-xs mb-5">Consulta pública</p><h2 className="text-4xl md:text-6xl font-black">Abierta, estable y sin registro.</h2><p className="text-gray-400 leading-relaxed max-w-2xl mt-7">Los documentos aparecerán con acceso directo únicamente cuando exista una versión oficial aprobada para publicación.</p><Link href="/transparencia" className="inline-flex mt-10 border border-white/30 px-6 py-4 uppercase tracking-[0.2em] text-xs font-bold hover:bg-white hover:text-black transition-all">Volver a Transparencia</Link></div></section><Footer /></main>;
}
